### PR TITLE
Move stuff around a bit

### PR DESCRIPTION
**Pull request by kviksilver**
A lot of stuff happening, detailed followup after all the work is done...

### CODE REVIEW

**Comment by ifreecarve** [comment]
I like this structure, but I'd prefer the `Illuminator` directory to be called `src` so that the cocoapods copies `illuminator/src` instead of `illuminator/Illuminator`.  I'm not going to merge this yet...not until we figure out the ruby gem stuff.

**Comment by ifreecarve** [comment]
I"m working on the updated command line docs, we should delay merging this until those are in.

**Comment by ifreecarve** [comment]
#26 may have messed up this PR.  I opened #29 which is this same request but rebased off master.

**Comment by kviksilver** [comment]
continue tracking it in https://github.com/paypal/Illuminator/pull/29

**Pull request closed without merging**
