### PR TITLE
Fix build error when PPAutomationBridge is built before UIKit is imported.

### PR DESCRIPTION
**Pull request by GriffinSchneider**

### CODE REVIEW

**Comment by djMax** [comment]
I was talking to Boris about this last week... Should be in an ifndef automation_udid because that's the only part that needs it. Else it won't work on OS X

**Comment by kviksilver** [comment]
Removing a dependency on UIDevice and initiating bridge with unique identifier might be best approach here... We can discuss it tomorrow.

**Comment by ifreecarve** [comment]
@kviksilver it's your call either way.

**Comment by djMax** [comment]
For me, since this is an iOS and/or Mac OS X lib, I think it's worth "making it easy" for the common case. In the case of Mac OS, I'd imagine it should be the computer name instead of device name, which is perhaps a worthwhile addition. But taking it out and making the app put together the name, even though it's just a few lines, seems almost punitive.

**Comment by GriffinSchneider** [comment]
I agree with Max. Updated the pullreq so that `PPAutomationBridge` is now possible to compile on OSX if you define `AUTOMATION_UDID`.

**Pull request merged**
